pipeline:
  log_path: '/home/rodolfo/Insync/rodolfopcruz2@gmail.com/Google Drive/Estudo/Projetos-Novos/Credit_card_fraud_detection/logs/pipeline_logs.log'
  experiment_name: 'Credit-Card-Fraud-Detection'


data_ingestion:
  dataset_path: '/home/rodolfo/Insync/rodolfopcruz2@gmail.com/Google Drive/Estudo/Projetos-Novos/Credit_card_fraud_detection/data/creditcard.csv'
  schema_path: '/home/rodolfo/Insync/rodolfopcruz2@gmail.com/Google Drive/Estudo/Projetos-Novos/Credit_card_fraud_detection/src/datapipeline/config/data_schema.yaml'

data_clean:
  target_column: 'Class'
  

